In [1]:
def ques(n):
    sum = 0
    series = []
    for i in range(1, n + 1):
        term = int('5' * i)
        series.append(term)
        sum = sum + term
    print(f"The series for n={n} is: ,",series)
    return sum
n = int(input("Enter the number of terms in the series: "))
print(f"The sum of the series for n={n} is: ",ques(n))

The series for n=5 is: , [5, 55, 555, 5555, 55555]
The sum of the series for n=5 is:  61725


In [2]:
y = [[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]]
y


[[15, 11, 11], [17, 16, 16], [15, 15, 18]]

In [3]:
# prompt:

import numpy as np

y = np.array([[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]])

print(y)


[[15 11 11]
 [17 16 16]
 [15 15 18]]


In [4]:
y[1,1]


16

In [5]:
arr = ([20,21,22,23,24,25,26,27,28,29])


In [9]:
import numpy as np
b = np.random.randint(1, 50, size=(6, 6))
b

array([[43, 18,  6, 16, 45, 20],
       [21, 22, 29, 49,  7, 49],
       [22, 27, 43, 33,  4, 14],
       [14, 21, 31, 29, 30, 39],
       [25,  5, 21, 42, 25, 22],
       [34, 22, 46, 18, 31, 15]])

In [7]:
y[(y>25) | (y%2!=0)]


array([15, 11, 11, 17, 15, 15])

In [8]:
y.sum(axis=0)


array([47, 42, 45])

### why we use log in ML ?
```
In machine learning, logarithmic transformations are commonly used to transform skewed data distributions into more normally distributed data.
This helps in improving the performance of machine learning models that assume normally distributed data, such as linear regression.
Log transformations can also help in handling large ranges of values and making the data more interpretable.
```

In [2]:
for i in range(1, 11):
    print(i, end=" ")
print()



1 2 3 4 5 6 7 8 9 10 
