In [1]:
def ques(n):
    sum = 0
    series = []
    for i in range(1, n + 1):
        term = int('5' * i)
        series.append(term)
        sum = sum + term
    print(f"The series for n={n} is: ,",series)
    return sum
n = int(input("Enter the number of terms in the series: "))
print(f"The sum of the series for n={n} is: ",ques(n))

The series for n=5 is: , [5, 55, 555, 5555, 55555]
The sum of the series for n=5 is:  61725


In [2]:
y = [[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]]
y


[[15, 11, 11], [17, 16, 16], [15, 15, 18]]

In [3]:
# prompt:

import numpy as np

y = np.array([[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]])

print(y)


[[15 11 11]
 [17 16 16]
 [15 15 18]]


In [4]:
y[1,1]


16

In [5]:
arr = ([20,21,22,23,24,25,26,27,28,29])


In [6]:
import numpy as np
b = np.random.randint(1, 50, size=(6, 6))
b

array([[ 8, 25, 30, 37, 34, 12],
       [38, 46,  9, 33, 32, 47],
       [13,  1, 47, 31, 27, 42],
       [34, 45, 34, 45, 47, 17],
       [12, 36, 49, 48,  4, 38],
       [14, 28, 37, 14, 30, 29]])

In [7]:
y[(y>25) | (y%2!=0)]


array([15, 11, 11, 17, 15, 15])

In [8]:
y.sum(axis=0)


array([47, 42, 45])

### why we use log in ML ?
```
In machine learning, logarithmic transformations are commonly used to transform skewed data distributions into more normally distributed data.
This helps in improving the performance of machine learning models that assume normally distributed data, such as linear regression.
Log transformations can also help in handling large ranges of values and making the data more interpretable.
```

In [9]:
for i in range(1, 11):
    print(i, end=" ")
print()



1 2 3 4 5 6 7 8 9 10 


### what is pandas ?  
-  pandas is a fast, powerful, flexible and easy to use open source data analysis
 and data manipulation library built on top of the Python programming language.


20/02/24 
>What is potential hetrogeneous data ? <br>
>What is potential columns ?

In [10]:
import pandas as pd
pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
pd.Series

pandas.core.series.Series

In [12]:
data=['a', 'b', 'c','d']
s = pd.Series(data)
s

0    a
1    b
2    c
3    d
dtype: object

In [13]:
data=['a', 'b', 'c','d','e']
s = pd.Series(data, index = [10, 2, 3, 4, 5])
s

10    a
2     b
3     c
4     d
5     e
dtype: object

In [14]:
data={'a':0., 'b':1., 'c':2.}
s = pd.Series(data)
s

a    0.0
b    1.0
c    2.0
dtype: float64

In [15]:
s.b

1.0

In [16]:
data={'a':0., 'b':1., 'c':2.}
s = pd.Series(data, index=['b', 'c', 'a', 'd','e'])
s

b    1.0
c    2.0
a    0.0
d    NaN
e    NaN
dtype: float64

In [17]:
s[0:3]

b    1.0
c    2.0
a    0.0
dtype: float64

In [18]:
s = pd.Series('abcd', index=[0, 1, 2, 3])
s

0    abcd
1    abcd
2    abcd
3    abcd
dtype: object

In [19]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'], dtype='int8')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int8


In [20]:
s[2:]

c    3
d    4
e    5
dtype: int8

In [21]:
data = [1, 2, 3, 4, 5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [22]:
data = [['Ram',10],['Jhon',12],['Ali',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0   Ram   10
1  Jhon   12
2   Ali   13

In [23]:
data ={'Name':['Ram','Jack','Jhon','Ali'],'Age':[10,12,13,14]}
df = pd.DataFrame(data, index=[1,2,3,4])
df


Name  Age
1   Ram   10
2  Jack   12
3  Jhon   13
4   Ali   14

In [24]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [25]:
df['two']
type(df.one)

pandas.core.series.Series

In [26]:
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df

one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [27]:
df['sum']=df['one']+df['two']
df

one  two  three  sum
a  1.0    1   10.0  2.0
b  2.0    2   20.0  4.0
c  3.0    3   30.0  6.0
d  NaN    4    NaN  NaN

In [ ]:
d = {'one': pd.Series([1, 2, 3,5], index=['a', 'b', 'c','d']),
 'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']),}

df = pd.DataFrame(d)
df

: 

In [29]:
df.loc['b':'d','two']

b    2
c    3
d    4
Name: two, dtype: int64

In [30]:
df.iloc[1:4,1]

b    2
c    3
d    4
Name: two, dtype: int64

In [31]:
a = df.drop('b')
a

one  two
a    1    1
c    3    3
d    5    4

In [32]:
s = pd.Series(np.random.randn(10), index=np.arange(1,11))
print(s)


1     0.785224
2     1.096898
3     0.076419
4     0.579147
5    -1.763424
6     0.902861
7     0.481838
8    -0.348558
9     1.224153
10   -1.029862
dtype: float64


In [33]:
s.empty

False

In [34]:
s.ndim

1

In [35]:
s.size

10

In [36]:
s.values

array([ 0.78522357,  1.09689804,  0.07641913,  0.57914651, -1.76342445,
        0.90286123,  0.48183792, -0.34855766,  1.22415341, -1.02986205])

In [37]:
s.head()

1    0.785224
2    1.096898
3    0.076419
4    0.579147
5   -1.763424
dtype: float64

In [38]:
s.tail(3)

8    -0.348558
9     1.224153
10   -1.029862
dtype: float64

In [39]:
print(s.min())

-1.7634244504792287


Transpose is temporary change

In [40]:
s.T

1     0.785224
2     1.096898
3     0.076419
4     0.579147
5    -1.763424
6     0.902861
7     0.481838
8    -0.348558
9     1.224153
10   -1.029862
dtype: float64

In [41]:
print(s)

1     0.785224
2     1.096898
3     0.076419
4     0.579147
5    -1.763424
6     0.902861
7     0.481838
8    -0.348558
9     1.224153
10   -1.029862
dtype: float64


In [42]:
s.axes

[Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int32')]

In [43]:
s.size

10

In [44]:
s.values

array([ 0.78522357,  1.09689804,  0.07641913,  0.57914651, -1.76342445,
        0.90286123,  0.48183792, -0.34855766,  1.22415341, -1.02986205])

In [45]:
s.info

<bound method Series.info of 1     0.785224
2     1.096898
3     0.076419
4     0.579147
5    -1.763424
6     0.902861
7     0.481838
8    -0.348558
9     1.224153
10   -1.029862
dtype: float64>

In [46]:
s.sum(0)

2.004695633336557

In [47]:
s.describe()

count    10.000000
mean      0.200470
std       0.977342
min      -1.763424
25%      -0.242313
50%       0.530492
75%       0.873452
max       1.224153
dtype: float64

In [48]:

from sklearn.compose import ColumnTransformer
from sklearn.datasets import fetch_openml
from sklearn.feature_selection import SelectPercentile, chi2
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
np.random.seed(0)

In [49]:
X,y = fetch_openml('titanic', version=1, as_frame=True, return_X_y=True)

In [50]:
X

pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female   
1          1                   Allison, Master. Hudson Trevor    male   
2          1                     Allison, Miss. Helen Loraine  female   
3          1             Allison, Mr. Hudson Joshua Creighton    male   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...      ...                                              ...     ...   
1304       3                             Zabour, Miss. Hileni  female   
1305       3                            Zabour, Miss. Thamine  female   
1306       3                        Zakarian, Mr. Mapriededer    male   
1307       3                              Zakarian, Mr. Ortin    male   
1308       3                               Zimmerman, Mr. Leo    male   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 13 columns]

In [51]:
y

0       1
1       1
2       0
3       0
4       0
       ..
1304    0
1305    0
1306    0
1307    0
1308    0
Name: survived, Length: 1309, dtype: category
Categories (2, object): ['0', '1']

In [52]:
X.count()

pclass       1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [53]:
y.count()

1309

In [54]:
y.unique()

['1', '0']
Categories (2, object): ['0', '1']

In [55]:
import pandas as pd

In [64]:
df = pd.read_csv(r'C:\Users\gaura\Desktop\Vool2024\AI-2024-main\AI-2024\data\titanic.csv')

In [65]:
df.head()

PassengerId   Survived       Pclass  \
1            0          3      "Braund   
2            1          1     "Cumings   
3            1          3   "Heikkinen   
4            1          1    "Futrelle   
5            0          3       "Allen   

   Name                                                                                  \
1   Mr. Owen Harris"                             ...                                      
2   Mrs. John Bradley (Florence Briggs Thayer)"  ...                                      
3   Miss. Laina"                                 ...                                      
4   Mrs. Jacques Heath (Lily May Peel)"          ...                                      
5   Mr. William Henry"                           ...                                      

    Sex      Age    SibSp   Parch   Ticket               Fare      \
1   male     22         1       0   A/5 21171              7.2500   
2   female   38         1       0   PC 17599              71.2833   
3   female   26         0       0   STON/O2. 3101282       7.9250   
4   female   35         1       0   113803                53.1000   
5   male     35         0       0   373450                 8.0500   

    Cabin            Embarked  
1                           S  
2   C85                     C  
3                           S  
4   C123                    S  
5                           S

In [66]:
df.tail()

PassengerId   Survived      Pclass  \
887            0          2   "Montvila   
888            1          1     "Graham   
889            0          3   "Johnston   
890            1          1       "Behr   
891            0          3     "Dooley   

     Name                                                                                  \
887   Rev. Juozas"                                 ...                                      
888   Miss. Margaret Edith"                        ...                                      
889   Miss. Catherine Helen ""Carrie"""            ...                                      
890   Mr. Karl Howell"                             ...                                      
891   Mr. Patrick"                                 ...                                      

      Sex      Age    SibSp   Parch   Ticket               Fare      \
887   male     27         0       0   211536                  13.00   
888   female   19         0       0   112053                  30.00   
889   female              1       2   W./C. 6607              23.45   
890   male     26         0       0   111369                  30.00   
891   male     32         0       0   370376                   7.75   

      Cabin            Embarked  
887                           S  
888   B42                     S  
889                           S  
890   C148                    C  
891                           Q

In [67]:
df.dtypes

PassengerId                                                                                int64
 Survived                                                                                  int64
 Pclass                                                                                   object
 Name                                                                                     object
 Sex                                                                                      object
 Age                                                                                      object
 SibSp                                                                                     int64
 Parch                                                                                     int64
 Ticket                                                                                   object
 Fare                                                                                    float64
 Cabin                        

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column                                                                                 Non-Null Count  Dtype  
---  ------                                                                                 --------------  -----  
 0   PassengerId                                                                            891 non-null    int64  
 1    Survived                                                                              891 non-null    int64  
 2    Pclass                                                                                891 non-null    object 
 3    Name                                                                                  891 non-null    object 
 4    Sex                                                                                   891 non-null    object 
 5    Age                                                                               

In [69]:
type(df[' Age '])

pandas.core.series.Series

In [75]:
df[' Age '].dtype

dtype('float64')

In [76]:
df[' Age '].shape

(891,)

In [77]:
df[' Age '] = pd.to_numeric(df[' Age '], errors='coerce')
df[' Age '] > 30


1      False
2       True
3      False
4       True
5       True
       ...  
887    False
888    False
889    False
890    False
891     True
Name:  Age , Length: 891, dtype: bool

In [70]:
multiple_columns = df[[' Name                                                                                ', ' Age ']]
multiple_columns

Name                                                                                  \
1     Mr. Owen Harris"                             ...                                     
2     Mrs. John Bradley (Florence Briggs Thayer)"  ...                                     
3     Miss. Laina"                                 ...                                     
4     Mrs. Jacques Heath (Lily May Peel)"          ...                                     
5     Mr. William Henry"                           ...                                     
..                                                 ...                                     
887   Rev. Juozas"                                 ...                                     
888   Miss. Margaret Edith"                        ...                                     
889   Miss. Catherine Helen ""Carrie"""            ...                                     
890   Mr. Karl Howell"                             ...                                     
891   Mr. Patrick"                                 ...                                     

      Age   
1     22    
2     38    
3     26    
4     35    
5     35    
..     ...  
887   27    
888   19    
889         
890   26    
891   32    

[891 rows x 2 columns]

In [72]:
df.columns

Index(['PassengerId', ' Survived', ' Pclass',
       ' Name                                                                                ',
       ' Sex   ', ' Age ', ' SibSp', ' Parch', ' Ticket            ',
       ' Fare    ', ' Cabin          ', ' Embarked'],
      dtype='object')

In [74]:
df[' Age '] = pd.to_numeric(df[' Age '], errors='coerce')
one = (df[' Age '] > 30) & (df[' Sex   '] == 'male')


In [78]:
num = one.sum()
num

0

In [79]:
multiple_columns = df[[' Name                                                                                ', ' Age ']]
multiple_columns

Name                                                                                  \
1     Mr. Owen Harris"                             ...                                     
2     Mrs. John Bradley (Florence Briggs Thayer)"  ...                                     
3     Miss. Laina"                                 ...                                     
4     Mrs. Jacques Heath (Lily May Peel)"          ...                                     
5     Mr. William Henry"                           ...                                     
..                                                 ...                                     
887   Rev. Juozas"                                 ...                                     
888   Miss. Margaret Edith"                        ...                                     
889   Miss. Catherine Helen ""Carrie"""            ...                                     
890   Mr. Karl Howell"                             ...                                     
891   Mr. Patrick"                                 ...                                     

     Age   
1    22.0  
2    38.0  
3    26.0  
4    35.0  
5    35.0  
..    ...  
887  27.0  
888  19.0  
889   NaN  
890  26.0  
891  32.0  

[891 rows x 2 columns]