In [1]:
def ques(n):
    sum = 0
    series = []
    for i in range(1, n + 1):
        term = int('5' * i)
        series.append(term)
        sum = sum + term
    print(f"The series for n={n} is: ,",series)
    return sum
n = int(input("Enter the number of terms in the series: "))
print(f"The sum of the series for n={n} is: ",ques(n))

The series for n=5 is: , [5, 55, 555, 5555, 55555]
The sum of the series for n=5 is:  61725


In [2]:
y = [[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]]
y


[[15, 11, 11], [17, 16, 16], [15, 15, 18]]

In [3]:
# prompt:

import numpy as np

y = np.array([[15, 11, 11],
     [17, 16, 16],
     [15, 15, 18]])

print(y)


[[15 11 11]
 [17 16 16]
 [15 15 18]]


In [4]:
y[1,1]


16

In [5]:
arr = ([20,21,22,23,24,25,26,27,28,29])


In [6]:
import numpy as np
b = np.random.randint(1, 50, size=(6, 6))
b

array([[ 2, 47, 25, 34,  3, 46],
       [17, 37, 23, 30,  6, 29],
       [29, 33,  4, 11, 29, 36],
       [10, 13, 23, 44, 40, 27],
       [43, 17, 23, 41, 18, 12],
       [38, 14, 12, 40, 43, 49]])

In [7]:
y[(y>25) | (y%2!=0)]


array([15, 11, 11, 17, 15, 15])

In [8]:
y.sum(axis=0)


array([47, 42, 45])

### why we use log in ML ?
```
In machine learning, logarithmic transformations are commonly used to transform skewed data distributions into more normally distributed data.
This helps in improving the performance of machine learning models that assume normally distributed data, such as linear regression.
Log transformations can also help in handling large ranges of values and making the data more interpretable.
```

In [9]:
for i in range(1, 11):
    print(i, end=" ")
print()



1 2 3 4 5 6 7 8 9 10 


### what is pandas ?  
-  pandas is a fast, powerful, flexible and easy to use open source data analysis
 and data manipulation library built on top of the Python programming language.


20/02/24 
>What is potential hetrogeneous data ? <br>
>What is potential columns ?

In [10]:
import pandas as pd
pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

C:\Users\gaura\AppData\Local\Temp\ipykernel_15936\3307055899.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
pd.Series

pandas.core.series.Series

In [12]:
data=['a', 'b', 'c','d']
s = pd.Series(data)
s

0    a
1    b
2    c
3    d
dtype: object

In [13]:
data=['a', 'b', 'c','d','e']
s = pd.Series(data, index = [10, 2, 3, 4, 5])
s

10    a
2     b
3     c
4     d
5     e
dtype: object

In [14]:
data={'a':0., 'b':1., 'c':2.}
s = pd.Series(data)
s

a    0.0
b    1.0
c    2.0
dtype: float64

In [15]:
s.b

1.0

In [16]:
data={'a':0., 'b':1., 'c':2.}
s = pd.Series(data, index=['b', 'c', 'a', 'd','e'])
s

b    1.0
c    2.0
a    0.0
d    NaN
e    NaN
dtype: float64

In [17]:
s[0:3]

b    1.0
c    2.0
a    0.0
dtype: float64

In [18]:
s = pd.Series('abcd', index=[0, 1, 2, 3])
s

0    abcd
1    abcd
2    abcd
3    abcd
dtype: object

In [19]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'], dtype='int8')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int8


In [20]:
s[2:]

c    3
d    4
e    5
dtype: int8

In [21]:
data = [1, 2, 3, 4, 5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [22]:
data = [['Ram',10],['Jhon',12],['Ali',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0   Ram   10
1  Jhon   12
2   Ali   13

In [23]:
data ={'Name':['Ram','Jack','Jhon','Ali'],'Age':[10,12,13,14]}
df = pd.DataFrame(data, index=[1,2,3,4])
df


Name  Age
1   Ram   10
2  Jack   12
3  Jhon   13
4   Ali   14

In [24]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [25]:
df['two']
type(df.one)

pandas.core.series.Series

In [26]:
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df

one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [27]:
df['sum']=df['one']+df['two']
df

one  two  three  sum
a  1.0    1   10.0  2.0
b  2.0    2   20.0  4.0
c  3.0    3   30.0  6.0
d  NaN    4    NaN  NaN

In [29]:
d = {'one': pd.Series([1, 2, 3,5], index=['a', 'b', 'c','d']),
 'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']),}

df = pd.DataFrame(d)
df

one  two
a    1    1
b    2    2
c    3    3
d    5    4

In [30]:
df.loc['b':'d','two']

b    2
c    3
d    4
Name: two, dtype: int64

In [35]:
df.iloc[1:4,1]

b    2
c    3
d    4
Name: two, dtype: int64

In [37]:
a = df.drop('b')
a

one  two
a    1    1
c    3    3
d    5    4

In [50]:
s = pd.Series(np.random.randn(10), index=np.arange(1,11))
print(s)


1    -0.607630
2     0.266445
3     1.250116
4    -1.752052
5     0.350246
6     0.583794
7     2.444467
8    -0.171785
9    -2.797489
10   -0.198096
dtype: float64


In [51]:
s.empty

False

In [52]:
s.ndim

1

In [53]:
s.size

10

In [54]:
s.values

array([-0.60763018,  0.26644468,  1.25011606, -1.7520518 ,  0.35024604,
        0.58379437,  2.44446744, -0.17178486, -2.79748864, -0.19809648])

In [58]:
s.head()

1   -0.607630
2    0.266445
3    1.250116
4   -1.752052
5    0.350246
dtype: float64

In [60]:
s.tail(3)

8    -0.171785
9    -2.797489
10   -0.198096
dtype: float64

In [61]:
print(s.min())

-2.7974886394099867


Transpose is temporary change

In [62]:
s.T

1    -0.607630
2     0.266445
3     1.250116
4    -1.752052
5     0.350246
6     0.583794
7     2.444467
8    -0.171785
9    -2.797489
10   -0.198096
dtype: float64

In [63]:
print(s)

1    -0.607630
2     0.266445
3     1.250116
4    -1.752052
5     0.350246
6     0.583794
7     2.444467
8    -0.171785
9    -2.797489
10   -0.198096
dtype: float64


In [64]:
s.axes

[Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int32')]

In [65]:
s.size

10

In [66]:
s.values

array([-0.60763018,  0.26644468,  1.25011606, -1.7520518 ,  0.35024604,
        0.58379437,  2.44446744, -0.17178486, -2.79748864, -0.19809648])

In [67]:
s.info

<bound method Series.info of 1    -0.607630
2     0.266445
3     1.250116
4    -1.752052
5     0.350246
6     0.583794
7     2.444467
8    -0.171785
9    -2.797489
10   -0.198096
dtype: float64>

In [71]:
s.sum(0)

-0.631983369289703

In [72]:
s.describe()

count    10.000000
mean     -0.063198
std       1.466907
min      -2.797489
25%      -0.505247
50%       0.047330
75%       0.525407
max       2.444467
dtype: float64